### ISSUE TITLE
hardcoded path to python?

### ISSUE THREAD

**Issue by github-4o** [personal-army-of-4o/spw_pkg_timeout#3]
https://github.com/personal-army-of-4o/spw_pkg_timeout/blob/921d93b40b14d642c3f2100812b7249ed2071856/test/Makefile#L7

@dmitrii-galantsev your local path?

**Comment by dmitrii-galantsev** [comment]
Think it's a leftover from sample cocotb test.
I think I was going to make a python model for it.
